"""Script used to generate the list of lines to be displayed by the help menu
It is necessary because binary files from Qt resources cannot be interpreted
properly"""

HELP_TEXT = ['# Membránrendszer szimulációs szoftver kézikönyv\n', '\n',
             '## A szoftverről\n', '\n',
             'Az alkalmazás célja, hogy segítségével a felhasználó membránrendszereket hozzon létre, majd szimulálni tudja\n',
             'számításaikat. A membránrendszer egy olyan biológiailag inspirált számítási modell, amely az eukarióta sejtek működését\n',
             'és felépítését követve evolúciós lépéseken keresztül történő információáramlást ír le membránok között. Minden membrán\n',
             'által körbezárt *régió* tartalmaz evolúciós szabályokat, amelyek nem változnak a membránrendszer működése közben. Az\n',
             'információt a rendszerben a régiókban található molekulák, *objektumok* hordozzák. Egy szabály csak akkor tud\n',
             'végbemenni, ha kellő számban rendelkezésre állnak a szükséges objektumok. Ilyen helyzetekben a szabályoknak végre is\n',
             'kell hajtódnia, tehát nem fordulhat elő, hogy minden objektum hozzáférhető, de nem kerül a szabály alkalmazásra. Egy\n',
             'evolúciós lépésben a maximális párhuzamosság elve érvényesül, azaz a szabályok véletszerűen kerülnek kiválasztása,\n',
             'egészen addig, amíg van alkalmazható szabály. Az alapmodellhez tartozó rendszerekben megadhatóak olyan speciális\n',
             'szabályok, amelyek alkalmazásának hatására egy membrán feloldódhat, ilyenkor teljes tartalma (benne levő objektumok és\n',
             'régiók) az őt körbevevő régióba kerülnek. A szabályok között prioritási sorrend is felállítható. A számítás legfontosabb\n',
             'tulajdonsága annak kimenete. A szoftver az alapmodell típusú rendszerek esetében a környezetbe kijutó, szimport-antiport\n',
             'rendszerek esetén pedig a kimeneti régióban található objektumok számát tekinti eredménynek.\n',
             '\n', '## Szoftver használata\n', '\n',
             'Az alkalmazás használata:\n', '\n',
             '1. Membránrendszer betöltése\n',
             '2. Membránrendszer testreszabása\n',
             '3. Membránrendszer lementése (Opcionális)\n',
             '4. Membránrendszer futtatása (lépésenként vagy a teljes számítás párhuzamosítva)\n',
             '\n', '## Betöltés\n', '\n',
             'Egy membránrendszer betöltéséhez két módot biztosít az alkalmazás:\n',
             '\n',
             '1. Mentett membránrendszer betöltése ( *Menü* => *Fájl* => *Betöltés*)\n',
             '    - Ilyenkor egy már meglévő fájlban lévő membránrendszer kerül betöltésre.\n',
             '2. Membránrendszer konstruálása a struktúra és objektumok megadásával ( *Menü* => *Membránstruktúra megadása* )\n',
             '    - Ilyenkor a felhasználónak kell a konstruálandó membránrendszer szöveges reprezentációját megadnia\n',
             '    - A szoftver két membránrendszer típus szimulálására alkalmas, ezekhez pedig valamelyest eltérő szöveges\n',
             '      reprezentációk tartoznak\n',
             '    - Általánosan zárójelek jelzik a régiók kezdetét és végét, ezek között találhatók a bennük jelen lévő objektumok.\n',
             '      Például egy alapmodell esetén "[aa[bb]]" a legkülső régió két darab \'a\' objektumot tartalmaz, míg a benne lévő (\n',
             "      gyerek) régió két darab 'b' objektumot\n",
             '    - Közös követelmények mindkét esetben\n',
             '        1. A megadott szövegben a zárójelezésnek helyesnek kell lennie (Minden nyitó zárójelnek van csukó párja, és\n',
             '           nincsenek átfedések)\n',
             '        2. Legalább egy zárójelpárt kell tartalmaznia a szövegnek\n',
             '\n', '    - Alapmodell\n',
             '        1. Alapmodell esetében ezen kívül feltétel, hogy a legkülső zárójelpáron kívül nem adhatunk meg objektumokat\n',
             '    - Szimport-antiport rendszer\n',
             '        1. Megadhatunk a legkülső zárójelpáron kívül is objektumokat, ezek fogják a környezet végtelenül rendelkezésre\n',
             '           álló objektumait szolgálni (Ha ugyanazon objektum többször szerepel, akkor is *csak* végtelen\n',
             '           multiplicitással lesz jelen a környezetben)\n',
             "        2. Tartalmaznia kell az egyik zárójelpárnak egy '#' szimbólumot, ami azt jelzi, hogy a számítás eredményét annak\n",
             '           a régiónak a tartalma fogja jelenteni (Ha több ilyet tartalmaz, akkor a feldolgozás során utoljára\n',
             '           feldolgozott jelenti a végleges kimeneti régiót)\n',
             '    - Meg kell jegyezni, hogy a struktúra és a benne lévő objektumok megadása nem elegendő ahhoz, hogy szimulálni\n',
             '      tudjunk egy membránrendszert, hiszen evolúciós szabályok nélkül nincs változás a rendszerben\n',
             '\n', '## Régiók szerkesztése\n', '\n',
             '- Egy régió objektumainak és szabályainak szerkesztéséhez duplán kell kattintani a régió belsejébe\n',
             '- Ilyenkor egy felugró ablakban külön szövegdobozban adhatjuk meg a régió új objektumait a felső szövegdobozban\n',
             '  (alapértelmezett szövegként jelenik meg a régió jelenlegi objektumhalmaza), illetve új szabályait.\n',
             '- Az objektumok csak az angol ábécé kisbetűiből állhatnak ([a-z])\n',
             '\n', '### Szabályok helyes formátuma\n', '\n',
             '- Mivel a programmal két típusú membránrendszer szimulálható, ezért ezek külön feltételeket szabnak a szabályaik\n',
             '  alakjáról\n', '- Alapmodell\n', '    - Általánosan:\n',
             '      *szükséges* ->(#) IN: *bevándorló* OUT: *kivándorló* HERE: *helyben*\n',
             '        - __szükséges__: A szabály úgynevezett bal oldala. Azokból az objektumokból áll, amelyeknek rendelkezésre kell állniuk a\n',
             '           régióban ahhoz, hogy végbemehessen az evolúciós lépés\n',
             '        - __bevándorló__: A szabály alkalmazásának következtében a szülőbe vándorló objektumok\n',
             '        - __kivándorló__: A szabály alkalmazásának következtében valamelyik gyerek régióba vándorló objektumok (nemdeterminisztikusan\n',
             '           választjuk ki, de csak akkor alkalmazható a szabály, ha legalább egy gyerekkel rendelkezik a régió)\n',
             '        - __helyben__: A szabály alkalmazásának következtében keletkező helyben maradó objektumok\n',
             "    - Ha a bal és jobb oldalt elválasztó nyíl végén egy '#' szimbólum található, az azt jelenti, hogy az adott régió a\n",
             '      szabály alkalmazása után felbomlik\n',
             '    - Üres bal oldallal nem konstruálható szabály\n',
             '    - Az objektumok ebben az esetben is csak az angol ábécé kisbetűi lehetnek\n',
             '    - Ezen kívül megadható még prioritásos szabály, amelynek alakja:\n',
             '      *erősebb_szabály* > *gyengébb szabály*\n',
             '        - Mindaddig nem alkalmazhatjuk a gyengébb szabályt, ameddig az erősebb alkalmazható.\n',
             '- Szimport-antiport modell\n', '    - Általánosan:\n',
             '      IN: *importált* OUT: *exportált* **VAGY** IN: *importált* **VAGY** OUT: *exportált*\n',
             '        - __importált__: A régióba beérkező objektumok\n',
             '        - __exportált__: A régióból kivándorló objektumok\n',
             '    - Fontos megjegyezni, hogy ha a legelső típusú (antiport) szabályt szeretnénk megadni, olyankor mindkét irányba\n',
             '      kötelező, hogy legalább egy objektum mozogjon\n', '\n',
             '## Mentés\n', '\n', '( *Menü* => *Mentés* )\n', '\n',
             '- A szoftver lehetőséget biztosít felhasználó által megadott membránrendszer aktuális állapotának elmentésére. Ez nagyon\n',
             '  hasznos tud lenni, hiszen ilyenkor nem kell minden alkalommal a struktúra megadásával majd szabályok hozzávételével\n',
             '  újraalkotni egy kezdőállapotot, hanem elegendő csak betölteni.\n',
             '- A mentés kezdeményezhető a menüsávból, de a **Ctrl+S** billentyűkombináció is hozzá van rendelve a funkcióhoz\n',
             '\n', '## Szimuláció futtatása\n', '\n',
             '- Miután a felhasználó megkonstruált egy membránrendszert, már csak egy dolog van hátra: szimulálni azt.\n',
             '- A szimuláláshoz két funkciót biztosít a program:\n',
             '    1. Lépésenkénti futtatás ( *Menü* => *Futtatás* => *Szimuláció lépés indítása*)\n',
             '        - Ilyenkor a membránrendszerben csak egy evolúció zajlik vége, azaz minden régióban alkalmazzuk a kiválasztott\n',
             '          szabályok multihalmazát\n',
             '    2. Párhuzamos szimuláció futtatása ( *Menü* => *Futtatás* => *Teljes szimuláció indítása*)\n',
             '        - Ilyenkor a felhasználónak meg kell adnia, hogy hány másolat készüljön a jelenlegi membránrendszerből. Miután\n',
             '          mindegyik másolat befejezte a számítást, az eredményeket tartalmazó összesító egy felugró dialógusablakban\n',
             '          jelenik meg.\n', '\n']

with open("./software_guide.md", 'r') as file:
    print(file.readlines())
